#!/usr/bin/env ruby
require "optparse"
require "next_rails/version"
require "next_rails"

options = {}
option_parser = OptionParser.new do |opts|
  opts.banner = <<-MESSAGE
    Usage: #{__FILE__.to_s} [options]

    Examples:
      bin/next_rails --version info # Show the version of the gem installed
  MESSAGE

  opts.on("--init", "Setup the dual-boot configuration") do
    options[:init] = true
  end

  opts.on("--version", "show version of the gem") do
    options[:version] = true
  end

  opts.on("--upgrade", "Rails version to check next upgrade target") do
    options[:upgrade] = true
  end

  opts.on_tail("-h", "--help", "Prints this help") do
    puts opts
    exit
  end

end

option_parser.parse!

puts NextRails::Init.call if options.fetch(:init, false)

if options.fetch(:version, false)
  puts NextRails::VERSION
  exit 2
end

if options.fetch(:upgrade, false)
  puts NextRails::Init.call(options[:upgrade])
  current_version = File.read("Gemfile.lock")[/^\s*rails \(([\d.]+)\)/, 1]
  url = ENV.fetch("UPGRADE_FROM_URL") { "https://roadrunner-staging-5ff1a4e7a439.herokuapp.com/api/v1/next_versions" }
  resp = NextRails::HttpClient.get(url, {current_rails_version: current_version})
  puts NextRails::UpgradeFrom.report(current_version, resp)

  return if resp["next_rails"].nil?

  rails_version = current_version == resp["current_latest_patch"] ? resp["next_rails"] : resp["current_latest_patch"]

  gems = NextRails::BundleReport.compatibility(rails_version: rails_version)
                                .prepend({name: "rails", version: rails_version})

  NextRails::UpgradeFrom.update_gemfile(gems)
end