#!/usr/bin/env ruby
require "optparse"
require "next_rails/version"
require "next_rails"
require 'byebug'

options = {}
option_parser = OptionParser.new do |opts|
  opts.banner = <<-MESSAGE
    Usage: #{__FILE__.to_s} [options]

    Examples:
      bin/next_rails --version info # Show the version of the gem installed
  MESSAGE

  opts.on("--version", "show version of the gem") do
    options[:version] = true
  end

  opts.on("--upgrade_from [STRING]", "Rails version to check next upgrade target") do |current_version|
    options[:current_version] = current_version
  end

  opts.on_tail("-h", "--help", "Prints this help") do
    puts opts
    exit
  end

end

option_parser.parse!

if options.fetch(:version, false)
  puts NextRails::VERSION
  exit 2
end

if options.fetch(:current_version, false)
  url = ENV.fetch("UPGRADE_FROM_URL") { "https://roadrunner-staging-5ff1a4e7a439.herokuapp.com/api/v1/next_versions" }
  resp = NextRails::HttpClient.get(url, {current_rails_version: options[:current_version]})
  puts NextRails::UpgradeFrom.report(options[:current_version], resp)
  NextRails::BundleReport.compatibility(rails_version: resp["next_rails"], ruby_version: nil, include_rails_gems: false)
end
